name: Build and Publish ShapeEngine NuGet Package

permissions:
   contents: read

on:
  workflow_dispatch:

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ShapeEngine/ShapeEngine.csproj

    - name: Build ShapeEngine
      run: dotnet build ShapeEngine/ShapeEngine.csproj --configuration Release --no-restore

    - name: Pack ShapeEngine NuGet Package
      run: dotnet pack ShapeEngine/ShapeEngine.csproj --configuration Release --no-build --output ./nupkgs

    - name: Publish ShapeEngine NuGet Package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        for pkg in ./nupkgs/*.nupkg; do
          dotnet nuget push "$pkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
        done
